server:
  port: 80
  context-path: 
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.132.104.23:3306/xyz_frame?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&&useSSL=false
    username: xyzframe
    password: xyzframe
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  data:
    mongodb:
      uri: mongodb://xyzframe:xyzframe@101.132.104.23:27017/xyz_frame
      # 集群配置 mongodb://xyzframe:xyzframe@172.16.0.140:27017,172.16.0.140:27018,172.16.0.140:27019/xyz_frame
    #
    # 静态资源
#    resources:
#    static-locations:
#      classpath:
#        static
    
task.run.flag:
  false
  
spring.redis.pool.max-active: 8
spring.redis.pool.max-wait: -1
spring.redis.pool.max-idle: 8
spring.redis.pool.min-idle: 0

spring.redis.hostName: 172.16.0.140
spring.redis.port: 6379
spring.redis.password: sider
spring.redis.timeout: 600000
spring.redis.database: 13

